stages:
  - test
test_job_1:
  stage: test
  script:
    - python Assignment1_API Testing_Automation.py
test_job_2:
  stage: test
  script:
    - python Assignment2_API Testing_Automation.py
test_job_3:
  stage: test
  script:
    - python Assignment3_API Testing_Automation.py